export const productCatalog = [
    {
        "id": 1,
        "name": "MacBook Air M2",
        "category": "Laptops",
        "price": 1199,
        "description": "13-inch laptop with M2 chip, 8GB RAM, 256GB SSD. Perfect for everyday computing and creative work.",
        "features": ["M2 chip", "13-inch Retina display", "All-day battery life", "Lightweight design", "macOS"],
        "brand": "Apple",
        "weight": "2.7 lbs",
        "battery_life": "18 hours",
        "use_cases": ["productivity", "creative work", "students", "professionals", "lightweight computing"]
    },
    {
        "id": 2,
        "name": "Dell XPS 13",
        "category": "Laptops", 
        "price": 999,
        "description": "13-inch Windows laptop with Intel i7, 16GB RAM, 512GB SSD. Great for business and productivity.",
        "features": ["Intel i7 processor", "13.3-inch 4K display", "16GB RAM", "512GB SSD", "Windows 11"],
        "brand": "Dell",
        "weight": "2.64 lbs",
        "battery_life": "12 hours",
        "use_cases": ["business", "productivity", "programming", "lightweight", "professionals"]
    },
    {
        "id": 3,
        "name": "Gaming Laptop ROG Strix",
        "category": "Laptops",
        "price": 1499,
        "description": "15-inch gaming laptop with RTX 4060, Intel i7, 16GB RAM, 1TB SSD. Built for high-performance gaming.",
        "features": ["NVIDIA RTX 4060", "Intel i7-12700H", "15.6-inch 144Hz display", "RGB keyboard", "Windows 11"],
        "brand": "ASUS",
        "weight": "5.07 lbs",
        "battery_life": "6 hours",
        "use_cases": ["gaming", "content creation", "video editing", "streaming", "high performance"]
    },
    {
        "id": 4,
        "name": "Lenovo ThinkPad X1 Carbon",
        "category": "Laptops",
        "price": 1399,
        "description": "14-inch business laptop with Intel i7, 16GB RAM, 512GB SSD. Enterprise-grade security and durability.",
        "features": ["Intel i7 processor", "14-inch 2.8K display", "Military-grade durability", "Fingerprint reader", "Windows 11 Pro"],
        "brand": "Lenovo",
        "weight": "2.48 lbs",
        "battery_life": "15 hours",
        "use_cases": ["business", "enterprise", "security", "durability", "professionals", "travel"]
    },
    {
        "id": 5,
        "name": "iPad Pro 12.9-inch",
        "category": "Tablets",
        "price": 1099,
        "description": "12.9-inch tablet with M2 chip, 128GB storage. Perfect for creative professionals and digital artists.",
        "features": ["M2 chip", "12.9-inch Liquid Retina XDR display", "Apple Pencil support", "Face ID", "iPadOS"],
        "brand": "Apple",
        "weight": "1.5 lbs",
        "battery_life": "10 hours",
        "use_cases": ["digital art", "note taking", "creative work", "media consumption", "presentations"]
    },
    {
        "id": 6,
        "name": "Samsung Galaxy Tab S9",
        "category": "Tablets",
        "price": 799,
        "description": "11-inch Android tablet with Snapdragon 8 Gen 2, 8GB RAM, 128GB storage. Great for productivity and entertainment.",
        "features": ["Snapdragon 8 Gen 2", "11-inch Super AMOLED display", "S Pen included", "DeX mode", "Android 13"],
        "brand": "Samsung",
        "weight": "1.1 lbs",
        "battery_life": "12 hours",
        "use_cases": ["productivity", "entertainment", "note taking", "android ecosystem", "multitasking"]
    },
    {
        "id": 7,
        "name": "Sony WH-1000XM5",
        "category": "Headphones",
        "price": 399,
        "description": "Premium noise-canceling wireless headphones with 30-hour battery life.",
        "features": ["Industry-leading noise cancellation", "30-hour battery", "Quick charge", "Multipoint connection", "High-res audio"],
        "brand": "Sony",
        "weight": "0.55 lbs",
        "battery_life": "30 hours",
        "use_cases": ["travel", "commuting", "music", "calls", "focus", "noise cancellation"]
    },
    {
        "id": 8,
        "name": "Apple AirPods Pro 2",
        "category": "Headphones",
        "price": 249,
        "description": "True wireless earbuds with active noise cancellation and spatial audio.",
        "features": ["Active noise cancellation", "Spatial audio", "H2 chip", "MagSafe charging", "IPX4 rating"],
        "brand": "Apple",
        "weight": "0.19 lbs",
        "battery_life": "6 hours + 24 hours with case",
        "use_cases": ["workouts", "commuting", "calls", "iOS ecosystem", "portable", "active lifestyle"]
    },
    {
        "id": 9,
        "name": "iPhone 15 Pro",
        "category": "Smartphones",
        "price": 999,
        "description": "6.1-inch smartphone with A17 Pro chip, 128GB storage, and advanced camera system.",
        "features": ["A17 Pro chip", "6.1-inch Super Retina XDR display", "48MP camera system", "Titanium design", "iOS 17"],
        "brand": "Apple",
        "weight": "0.41 lbs",
        "battery_life": "23 hours video playback",
        "use_cases": ["photography", "videography", "iOS ecosystem", "premium experience", "everyday use"]
    },
    {
        "id": 10,
        "name": "Samsung Galaxy S24 Ultra",
        "category": "Smartphones",
        "price": 1199,
        "description": "6.8-inch smartphone with Snapdragon 8 Gen 3, 256GB storage, and S Pen support.",
        "features": ["Snapdragon 8 Gen 3", "6.8-inch Dynamic AMOLED 2X", "200MP camera", "S Pen", "Android 14"],
        "brand": "Samsung",
        "weight": "0.51 lbs",
        "battery_life": "28 hours video playback",
        "use_cases": ["productivity", "note taking", "photography", "large screen", "android ecosystem", "power users"]
    },
    {
        "id": 11,
        "name": "Google Pixel 8",
        "category": "Smartphones",
        "price": 699,
        "description": "6.2-inch smartphone with Google Tensor G3, 128GB storage, and pure Android experience.",
        "features": ["Google Tensor G3", "6.2-inch Actua display", "50MP camera with AI", "7 years of updates", "Pure Android"],
        "brand": "Google",
        "weight": "0.42 lbs",
        "battery_life": "24 hours",
        "use_cases": ["photography", "AI features", "pure android", "updates", "Google ecosystem"]
    },
    {
        "id": 12,
        "name": "Monitor 4K 27-inch",
        "category": "Monitors",
        "price": 499,
        "description": "27-inch 4K monitor with USB-C connectivity and color accuracy for professionals.",
        "features": ["4K resolution", "27-inch IPS display", "USB-C hub", "99% sRGB", "Height adjustable"],
        "brand": "LG",
        "weight": "12.1 lbs",
        "battery_life": "N/A",
        "use_cases": ["design work", "programming", "productivity", "content creation", "multi-tasking", "home office"]
    },
    {
        "id": 13,
        "name": "Mechanical Keyboard RGB",
        "category": "Keyboards",
        "price": 149,
        "description": "Wireless mechanical keyboard with RGB backlighting and tactile switches.",
        "features": ["Mechanical switches", "RGB backlighting", "Wireless connectivity", "Hot-swappable keys", "Aluminum frame"],
        "brand": "Keychron",
        "weight": "2.2 lbs",
        "battery_life": "240 hours",
        "use_cases": ["gaming", "programming", "typing", "productivity", "customization", "enthusiasts"]
    },
    {
        "id": 14,
        "name": "Wireless Mouse Pro",
        "category": "Mice",
        "price": 99,
        "description": "Ergonomic wireless mouse with precision tracking and long battery life.",
        "features": ["Ergonomic design", "Precision sensor", "Wireless connectivity", "Customizable buttons", "Long battery life"],
        "brand": "Logitech",
        "weight": "0.24 lbs",
        "battery_life": "70 days",
        "use_cases": ["productivity", "design work", "gaming", "comfort", "precision", "office work"]
    },
    {
        "id": 15,
        "name": "Webcam 4K Ultra",
        "category": "Webcams",
        "price": 199,
        "description": "4K webcam with auto-focus and noise-canceling microphone for video calls.",
        "features": ["4K resolution", "Auto-focus", "Noise-canceling microphone", "Wide field of view", "Plug and play"],
        "brand": "Logitech",
        "weight": "0.58 lbs",
        "battery_life": "N/A",
        "use_cases": ["video calls", "streaming", "content creation", "remote work", "meetings", "professional"]
    }
];
